name: Process New Content

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  issues: read

jobs:
  process-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Debug Issue Labels
        run: |
          echo "Issue Labels: ${{ toJSON(github.event.issue.labels) }}"
          
      - name: Create directories
        run: |
          mkdir -p data
          mkdir -p art
          mkdir -p photos
          mkdir -p journal
          mkdir -p cat
      
      - name: Process Issue Content
        run: |
          # Create issue data file
          echo '${{ toJSON(github.event.issue) }}' > issue_data.json
          
          # Run the processing script
          node .github/scripts/process-content.js
        
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Add new content from issue #${{ github.event.issue.number }}'
          add: '.'
          default_author: github_actions
