
name: New Art Entry
description: Add a new artwork to the archive
title: "[ART]: "
labels: ["content", "art"]
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: Title of the artwork
      placeholder: "shadow study #3"
    validations:
      required: true
  
  - type: input
    id: description
    attributes:
      label: Description
      description: Medium and dimensions
      placeholder: "charcoal on paper, 18×24\""
    validations:
      required: true
      
  - type: textarea
    id: content
    attributes:
      label: Content
      description: Details about the artwork
      placeholder: Write about this artwork...
    validations:
      required: true

  - type: input
    id: image
    attributes:
      label: Image URL (optional)
      description: Link to an image if available
      placeholder: https://example.com/image.jpg
    validations:
      required: false
