
name: New Photo Entry
description: Add a new photo to the archive
title: "[PHOTO]: "
labels: ["content", "photos"]
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: Title of the photo
      placeholder: "sunset fragments"
    validations:
      required: true
  
  - type: input
    id: description
    attributes:
      label: Description
      description: Camera and location
      placeholder: "digital, downtown"
    validations:
      required: true
      
  - type: textarea
    id: content
    attributes:
      label: Content
      description: Details about the photo
      placeholder: Write about this photo...
    validations:
      required: true

  - type: input
    id: image
    attributes:
      label: Image URL (optional)
      description: Link to the photo if available
      placeholder: https://example.com/image.jpg
    validations:
      required: false
